
/**
* iorfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* vendredi 3 mars 2017 11 h 26 CET
*/

public interface iorfile
{
  public static final String value = "annu.ior";
}
