package Etudiants;


/**
* Etudiants/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiants.idl
* mardi 14 mars 2017 08 h 36 CET
*/

public interface Etudiant extends EtudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
