
/**
* _CompteStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* mardi 14 mars 2017 08 h 36 CET
*/

public class _CompteStub extends org.omg.CORBA.portable.ObjectImpl implements Compte
{


  // Déposer un certain montant sur un compte
  public void deposeLiquide (float Flottant)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deposeLiquide", true);
                $out.write_float (Flottant);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deposeLiquide (Flottant        );
            } finally {
                _releaseReply ($in);
            }
  } // deposeLiquide


  // Retirer dargent du compte (mais vous nautorisez pas le découvert !)
  public boolean retireLiquide (float Flottant)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("retireLiquide", true);
                $out.write_float (Flottant);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return retireLiquide (Flottant        );
            } finally {
                _releaseReply ($in);
            }
  } // retireLiquide


  // Afficher le montant deposé sur le compte
  public float afficheMontant ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("afficheMontant", true);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return afficheMontant (        );
            } finally {
                _releaseReply ($in);
            }
  } // afficheMontant


  // et false est retournée
  public boolean virementCompteaCompte (float Flottant, int Compte)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("virementCompteaCompte", true);
                $out.write_float (Flottant);
                $out.write_long (Compte);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return virementCompteaCompte (Flottant, Compte        );
            } finally {
                _releaseReply ($in);
            }
  } // virementCompteaCompte

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Compte:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CompteStub
