
/**
* CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* mardi 14 mars 2017 08 h 36 CET
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompteHelper.type ();
  }

}
