
/**
* ICouleurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICouleur.idl
* vendredi 3 mars 2017 10 h 39 CET
*/

public abstract class ICouleurPOA extends org.omg.PortableServer.Servant
 implements ICouleurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setColorRGB", new java.lang.Integer (0));
    _methods.put ("getColorRGB", new java.lang.Integer (1));
    _methods.put ("getLuminance", new java.lang.Integer (2));
    _methods.put ("getColorCMY", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ICouleur/setColorRGB
       {
         double red = in.read_double ();
         double green = in.read_double ();
         double blue = in.read_double ();
         this.setColorRGB (red, green, blue);
         out = $rh.createReply();
         break;
       }

       case 1:  // ICouleur/getColorRGB
       {
         org.omg.CORBA.DoubleHolder red = new org.omg.CORBA.DoubleHolder ();
         org.omg.CORBA.DoubleHolder green = new org.omg.CORBA.DoubleHolder ();
         org.omg.CORBA.DoubleHolder blue = new org.omg.CORBA.DoubleHolder ();
         this.getColorRGB (red, green, blue);
         out = $rh.createReply();
         out.write_double (red.value);
         out.write_double (green.value);
         out.write_double (blue.value);
         break;
       }

       case 2:  // ICouleur/getLuminance
       {
         double $result = (double)0;
         $result = this.getLuminance ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // ICouleur/getColorCMY
       {
         org.omg.CORBA.DoubleHolder cyan = new org.omg.CORBA.DoubleHolder ();
         org.omg.CORBA.DoubleHolder magenta = new org.omg.CORBA.DoubleHolder ();
         org.omg.CORBA.DoubleHolder yellow = new org.omg.CORBA.DoubleHolder ();
         this.getColorCMY (cyan, magenta, yellow);
         out = $rh.createReply();
         out.write_double (cyan.value);
         out.write_double (magenta.value);
         out.write_double (yellow.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ICouleur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICouleur _this() 
  {
    return ICouleurHelper.narrow(
    super._this_object());
  }

  public ICouleur _this(org.omg.CORBA.ORB orb) 
  {
    return ICouleurHelper.narrow(
    super._this_object(orb));
  }


} // class ICouleurPOA
