
/**
* IcarreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 3 mars 2017 10 h 42 CET
*/

public interface IcarreOperations 
{
  int carre (int source);
} // interface IcarreOperations
