
/**
* _ICouleurImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICouleur.idl
* vendredi 3 mars 2017 10 h 38 CET
*/

public abstract class _ICouleurImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements ICouleur, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ICouleurImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setColorRGB", new java.lang.Integer (0));
    _methods.put ("getLuminance", new java.lang.Integer (1));
    _methods.put ("getC", new java.lang.Integer (2));
    _methods.put ("getM", new java.lang.Integer (3));
    _methods.put ("getY", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ICouleur/setColorRGB
       {
         double red = in.read_double ();
         double green = in.read_double ();
         double blue = in.read_double ();
         this.setColorRGB (red, green, blue);
         out = $rh.createReply();
         break;
       }

       case 1:  // ICouleur/getLuminance
       {
         double $result = (double)0;
         $result = this.getLuminance ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // ICouleur/getC
       {
         double $result = (double)0;
         $result = this.getC ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // ICouleur/getM
       {
         double $result = (double)0;
         $result = this.getM ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // ICouleur/getY
       {
         double $result = (double)0;
         $result = this.getY ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ICouleur:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ICouleurImplBase
