
/**
* ICouleurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICouleur.idl
* vendredi 3 mars 2017 10 h 38 CET
*/

public final class ICouleurHolder implements org.omg.CORBA.portable.Streamable
{
  public ICouleur value = null;

  public ICouleurHolder ()
  {
  }

  public ICouleurHolder (ICouleur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ICouleurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ICouleurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ICouleurHelper.type ();
  }

}
