
/**
* ICouleur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICouleur.idl
* vendredi 3 mars 2017 10 h 38 CET
*/

public interface ICouleur extends ICouleurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICouleur
