
/**
* ICouleurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICouleur.idl
* vendredi 3 mars 2017 10 h 38 CET
*/

public interface ICouleurOperations 
{
  void setColorRGB (double red, double green, double blue);
  double getLuminance ();
  double getC ();
  double getM ();
  double getY ();
} // interface ICouleurOperations
